### ISSUE TITLE
[Task]: Github Actions checks should block merging PRs

### ISSUE THREAD

**Issue by daphnegold** [HHS/grants-equity#286]
### Summary

Blocked by #110, #109 

Github Actions checks (tests passing, etc) should stop PRs from merging until they pass. A repo admin will need to pick up this task.

### Acceptance criteria

- [x] Configure Github Actions to block PR merge until they pass

**Comment by widal001** [comment]
Branch protections requiring checks to pass before merge have been enabled for `main`:

<img width="783" alt="Screenshot 2023-07-21 at 9 10 41 AM" src="https://github.com/HHS/grants-equity/assets/21350331/0affbcdf-5170-498a-bfc9-ec26fca15584">

@daphnegold can we work on standardizing the naming conventions of the checks to make it easier to figure out which ones need to be enabled?

**Comment by widal001** [comment]
Actually it looks like this might be a bit more complicated to enable in a monorepo when the GitHub actions are set up to only run when changes are made to certain paths: [see this discussion](https://github.com/orgs/community/discussions/26251)

The problem is that if a PR doesn't trigger a run for all tests (because it only contains code changes for one branch) then it will block the merge, you can see the issue on [this PR for an ADR](https://github.com/HHS/grants-equity/pull/307): 

<img width="1440" alt="Screenshot 2023-07-21 at 9 18 01 AM" src="https://github.com/HHS/grants-equity/assets/21350331/614406b4-42c0-4432-81f1-e34c3622f95f">

**Comment by daphnegold** [comment]
@widal001 and I discussed offline, and going to hold off on more engineering to make this happen right now. What's expected is that anyone with write access is trustworthy and conscientious enough to make sure their PR is passing before merging. We will revisit this topic again in the future! Note that while this does mean that a PR can be merged without passing checks, a production deploy should never complete without passing all the checks. That is a requirement of our CI/CD pipeline. ICs are responsible for breaking the build and failure to deploy right now.

Also making a little ticket so myself (or whoever) doesn't forget to do the standardization of check naming so we know which is which. Great point!
