### ISSUE TITLE
[Spike]: Document replication and transformation strategies for production database

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#388]
## Description

Once we have identified the initial API needs, see #70, we will need to get data from the production database in order to provide opportunity information.

For testing purposes, we can use fixture data created in the API. There is another ticket for this.

There are several components.

### Replication

We will need to get updated data from the existing grants.gov database. We will likely use the AWS DMS tool for this.

Questions include whether we would pull in all of the data updates or only specific tables.

Replication would require that journaling is turned on on the existing Oracle database, and would affect that resource utilization of that database.

### Transformation

We will undoubtedly need to do some kind of transformation once we have features that use the database. This may involve changing the data types of existing columns, creating new views to better support the API or aother analysis, or data cleaning.

The DMS tool supports this, however we may want to build our own transformation pipeline. A tool like dbt might be a good fit. In that case we would likely use an ELT strategy, first getting replicated data, then transforming it. The ADR could leave this decision for future work.

### New Data Model

Once we start working on #70, we may want to store the data differently than in the current system. If this is the case we can describe that as changing or creating a new data model. If we change the data model then we will need to incorporate this in the transformation step.

### Connecting to Test and Prod database

The spike should consider exactly what access point needs to be setup to peer between the VPCs in AWS, or if there is another connection strategy. This discovery should also note what other steps like turning on journaling will be necessary.

### Questions to answer

1. Do we want to replicate the database at all right now? 
2. Do we want to replicate the entire database or just specific tables for get_opportunities endpoint? (what is easiest is okay for us)
3. What will we do for test data in our dev environment/local development?

### Open Questions / Notes
  - Separate this into it's own task - Local dev data strategy (use of fixture data vs connecting to dev or prod AWS envs)

### Definition of Done

- [x] A comment in this ticket or a page in the internal wiki documenting 
  - [x] Replication strategy (ie DMS, certain tables)
  - [x] Initial transformation strategy 
  - [x] Description of different environments (dev / prod)
- [x] AWS budget has been updated if necessary
- [x] Steps that MH will need to take to support the decision will be recorded, such as turning on journaling or network setup
- [x] List of high level tasks that can be turned into tickets in order to start development

### 

After this spike, we should be able to:

* Write the #322 
* Create an initial epic, ie "Setup DMS Tool and Dev Database Replication" with a backlog of tasks
* Define following epics to define replication work

**Comment by SammySteiner** [comment]
## High Level Summary

After looking into AWS best practices for replication, it seems like AWS DMS (Data Migration Service) for cross vpc replication is the way to go.

Gina wrote a good doc evaluating DMS for our needs here: https://docs.google.com/document/d/1UwgbwHHSRAqUaIF07uXWS2AQGD3A8vx-w4maqQUYHvQ/edit

To summarize, DMS is AWS intended tool for our use case, it is Fedramp approved, and can support our technical requirements.

## Replication Tool (ie DMS, certain tables)
With DMS we can limit the replication to only certain tables, which can reduce storage costs until we're ready to use more than just the opportunities data. Additionally, opportunities data is public and not sensitive, which will reduce the criticality of our security posture.

## Initial Transformation Strategy
While DMS supports data translations, we do not yet have a clear understanding of the schema changes that are necessary to improve querying for the API, so there is no utility in taking that on until the schema itself is impacting our query duration.

## Description of different environments (dev / prod)
We will configure DMS using Terraform as infrastructure as code. This will allow us to use the lower environment Microhealth database for our lower environment's source database and confirm that we have configured the tool correctly in code before deploying that against the production database. The only difference between environments should be the source database hostname.

## AWS budget has been updated if necessary
Because we're only replicating some of the tables and not the entire database, we will hopefully be well within our budget for this performance period. There will be an additional cost for transferring data from the source database VPC if it is in a different AZ.

## Steps that MH will need to take
Microhealth will need to allow the DMS tool from our AWS VPC (virtual private cloud) to connect to their database in their AWS VPC. The way AWS recommends configuring this is with VPC Peering, discussed here: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReplicationInstance.VPC.html#CHAP_ReplicationInstance.VPC.Configurations.ScenarioVPCPeer
Implementation details for VPC Peering can be found here: https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html
Additionally it will save us money to keep the target and source database in the same AWS AZ (availability zone), so we'll need to know which AZ that the MH database resides.
We will also need Microhealth to configure access permission to their database from our DMS instance.

## List of tasks
1. Create and ADR documenting this approach
2. Create the target PostgreSQL RDS in Terraform code
3. Create the DMS instance in Terraform code
  * Important: for migration type, select ‘Migrate existing data and replicate ongoing changes’
  * Limit tables to just opportunities data in DMS
  * get AZ info from Microhealth 
  * Microhealth to configure access permissions
  * get hostname, port, and any other access information
4. Work with Microhealth to configure VPC Peering

**Comment by daphnegold** [comment]
The only thing I was thinking on is whether we want to set up DMS for the dev AWS instance, and I think it's worthwhile. Alternative being dev just having a static dump of a subset of the data or something.

- We can test and mess up and learn there until we are experts and get the database to a more solid state
- We are a data heavy project where we will likely be messing with it for the foreseeable future so this sets us up for success
- Because of above, DMS likely part of our future endeavors with data pipelines/adding and removing tables/updating schema
- We can always delete it later and just have a static dump of data in RDS if we don't need it at some point
- Increased consistency across environments

All this outweighs cost con in favor of convenience, stability and consistency across environments. And you made a great point that since we are only replicating a subset of the data, we will likely be budgeting fine. And also we can adjust budget!
